-- MySQL Script generated by MySQL Workbench
-- Sat Sep 27 21:20:14 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8mb4 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`gold_price`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`gold_price` (
  `PRICE_ID` BIGINT NOT NULL AUTO_INCREMENT COMMENT '금 시세 고유 ID',
  `PRICE_DATE` DATE NOT NULL COMMENT '시세 날짜',
  `PRICE_PER_G` DECIMAL(15,2) NOT NULL COMMENT '금 시세 (원/g)',
  `CHANGE_RATE` FLOAT NULL DEFAULT NULL COMMENT '변동률 (%)',
  PRIMARY KEY (`PRICE_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COMMENT = '금 시세 테이블';


-- -----------------------------------------------------
-- Table `mydb`.`members`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`members` (
  `MEMBER_NO` BIGINT NOT NULL AUTO_INCREMENT COMMENT '회원 고유 ID',
  `MEMBER_ID` VARCHAR(50) NOT NULL COMMENT '로그인 ID',
  `MEMBER_PWD` VARCHAR(255) NOT NULL COMMENT '비밀번호(해시)',
  `MEMBER_NAME` VARCHAR(100) NOT NULL COMMENT '사용자 이름',
  `MEMBER_EMAIL` VARCHAR(100) NOT NULL COMMENT '회원 이메일',
  `MEMBER_ROLE` VARCHAR(20) NULL DEFAULT 'USER' COMMENT '권한(USER/ADMIN)',
  `MEMBER_CREATED_AT` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT '가입일시',
  `MEMBER_UPDATED_AT` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '정보 수정일시',
  `MEMBER_LAST_LOGIN_AT` TIMESTAMP NULL DEFAULT NULL COMMENT '최근 로그인 시간',
  `MEMBER_IS_ACTIVE` TINYINT(1) NULL DEFAULT '1' COMMENT '계정 활성 여부',
  `MEMBER_DELETED_AT` TIMESTAMP NULL DEFAULT NULL COMMENT '계정 삭제 시간',
  PRIMARY KEY (`MEMBER_NO`),
  UNIQUE INDEX `MEMBER_ID` (`MEMBER_ID` ASC) VISIBLE,
  UNIQUE INDEX `MEMBER_EMAIL` (`MEMBER_EMAIL` ASC) VISIBLE,
  INDEX `IDX_MEMBERS_DELETED_AT` (`MEMBER_DELETED_AT` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COMMENT = '회원 정보 테이블';


-- -----------------------------------------------------
-- Table `mydb`.`member_auth`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`member_auth` (
  `NO` BIGINT NOT NULL AUTO_INCREMENT,
  `MEMBER_ID` VARCHAR(50) NOT NULL,
  `AUTH` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`NO`),
  INDEX `FK_AUTH_MEMBER` (`MEMBER_ID` ASC) VISIBLE,
  CONSTRAINT `FK_AUTH_MEMBER`
    FOREIGN KEY (`MEMBER_ID`)
    REFERENCES `mydb`.`members` (`MEMBER_ID`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COMMENT = '회원 권한';


-- -----------------------------------------------------
-- Table `mydb`.`news_article`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`news_article` (
  `ARTICLE_ID` BIGINT NOT NULL AUTO_INCREMENT COMMENT '기사 고유 ID',
  `ARTICLE_DATE` DATE NOT NULL COMMENT '기사 날짜',
  `ARTICLE_TITLE` VARCHAR(500) NOT NULL COMMENT '기사 제목',
  `ARTICLE_CONTENT` TEXT NOT NULL COMMENT '기사 본문(첫 줄)',
  `URL` VARCHAR(1000) NOT NULL COMMENT '기사 원문 링크',
  `SOURCE_NAME` VARCHAR(255) NULL DEFAULT NULL COMMENT '언론사명',
  `SENTIMENT_SCORE` FLOAT NULL DEFAULT NULL COMMENT '감성 점수 (AI 분석 결과)',
  `SUMMARY` TEXT NULL DEFAULT NULL COMMENT 'AI 요약 결과',
  `IS_CRAWLABLE` TINYINT(1) NULL DEFAULT '1' COMMENT '크롤링 가능 여부 (1=가능, 0=불가)',
  `CREATED_AT` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
  PRIMARY KEY (`ARTICLE_ID`),
  INDEX `IDX_NEWS_DATE` (`ARTICLE_DATE` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COMMENT = '뉴스 기사 테이블';


-- -----------------------------------------------------
-- Table `mydb`.`persistent_logins`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`persistent_logins` (
  `USERNAME` VARCHAR(64) NOT NULL,
  `SERIES` VARCHAR(64) NOT NULL,
  `TOKEN` VARCHAR(64) NOT NULL,
  `LAST_USED` TIMESTAMP NOT NULL,
  PRIMARY KEY (`SERIES`),
  INDEX `IDX_PLOGIN_USERNAME` (`USERNAME` ASC) VISIBLE,
  CONSTRAINT `FK_PLOGIN_MEMBER`
    FOREIGN KEY (`USERNAME`)
    REFERENCES `mydb`.`members` (`MEMBER_ID`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COMMENT = '스프링 remember-me 토큰';


-- -----------------------------------------------------
-- Table `mydb`.`simulation_history`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`simulation_history` (
  `HISTORY_NO` BIGINT NOT NULL AUTO_INCREMENT COMMENT '이력 고유 ID',
  `MEMBER_NO` BIGINT NOT NULL COMMENT '회원 PK(FK)',
  `HISTORY_DATE` DATE NOT NULL COMMENT '실행 날짜',
  `HISTORY_TYPE` VARCHAR(20) NOT NULL DEFAULT '매수' COMMENT '거래 타입(매수/매도)',
  `HISTORY_PREDICT` VARCHAR(20) NULL DEFAULT NULL COMMENT '예측(상승/하락)',
  `HISTORY_RESULT` VARCHAR(20) NULL DEFAULT NULL COMMENT '실제(NULL=미풀이)',
  `PNL` DECIMAL(10,2) NULL DEFAULT NULL COMMENT '손익',
  `FAVORITE` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '즐겨찾기',
  `TAGS` VARCHAR(255) NULL DEFAULT NULL COMMENT '태그 콤마 구분',
  `NOTE` TEXT NULL DEFAULT NULL COMMENT '메모',
  `CREATED_AT` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 시각',
  PRIMARY KEY (`HISTORY_NO`),
  INDEX `FK_HIST_MEMBER` (`MEMBER_NO` ASC) VISIBLE,
  CONSTRAINT `FK_HIST_MEMBER`
    FOREIGN KEY (`MEMBER_NO`)
    REFERENCES `mydb`.`members` (`MEMBER_NO`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COMMENT = '회원별 시뮬레이션 이력';


-- -----------------------------------------------------
-- Table `mydb`.`simulation_trade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`simulation_trade` (
  `TRADE_NO` BIGINT NOT NULL AUTO_INCREMENT COMMENT '거래 고유 ID',
  `MEMBER_NO` BIGINT NOT NULL COMMENT '회원 PK(FK)',
  `TRADE_DATE` DATE NOT NULL COMMENT '거래 날짜',
  `TRADE_TYPE` VARCHAR(10) NOT NULL COMMENT '매수/매도',
  `GOLD_PRICE` DECIMAL(10,2) NOT NULL COMMENT '거래 당시 금 시세(원/g)',
  `QUANTITY` DECIMAL(10,3) NOT NULL COMMENT '거래 수량(g)',
  `AMOUNT` DECIMAL(15,2) NOT NULL COMMENT '거래 총액(원)',
  `CREATED_AT` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT '거래 생성 시각',
  PRIMARY KEY (`TRADE_NO`),
  INDEX `FK_TRADE_MEMBER` (`MEMBER_NO` ASC) VISIBLE,
  CONSTRAINT `FK_TRADE_MEMBER`
    FOREIGN KEY (`MEMBER_NO`)
    REFERENCES `mydb`.`members` (`MEMBER_NO`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COMMENT = '회원별 거래 기록';


-- -----------------------------------------------------
-- Table `mydb`.`simulation_result`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`simulation_result` (
  `RESULT_NO` BIGINT NOT NULL AUTO_INCREMENT COMMENT '결과 고유 ID',
  `TRADE_NO` BIGINT NOT NULL COMMENT '연결된 거래 PK',
  `MEMBER_NO` BIGINT NOT NULL COMMENT '회원 PK(FK)',
  `RESULT_DATE` DATE NOT NULL COMMENT '결과 날짜',
  `PNL` DECIMAL(10,2) NULL DEFAULT NULL COMMENT '손익',
  `PREDICT` VARCHAR(20) NULL DEFAULT NULL COMMENT '예측(상승/하락)',
  `ACTUAL` VARCHAR(20) NULL DEFAULT NULL COMMENT '실제 결과(NULL=미풀이)',
  `FAVORITE` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '즐겨찾기',
  `NOTE` TEXT NULL DEFAULT NULL COMMENT '메모',
  `CREATED_AT` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 시각',
  PRIMARY KEY (`RESULT_NO`),
  INDEX `FK_RESULT_TRADE` (`TRADE_NO` ASC) VISIBLE,
  INDEX `FK_RESULT_MEMBER` (`MEMBER_NO` ASC) VISIBLE,
  CONSTRAINT `FK_RESULT_MEMBER`
    FOREIGN KEY (`MEMBER_NO`)
    REFERENCES `mydb`.`members` (`MEMBER_NO`)
    ON DELETE CASCADE,
  CONSTRAINT `FK_RESULT_TRADE`
    FOREIGN KEY (`TRADE_NO`)
    REFERENCES `mydb`.`simulation_trade` (`TRADE_NO`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COMMENT = '회원별 거래 결과 및 손익';

USE `mydb` ;

-- -----------------------------------------------------
-- Placeholder table for view `mydb`.`v_history_base`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`v_history_base` (`HISTORY_NO` INT, `MEMBER_NO` INT, `HISTORY_DATE` INT, `HISTORY_PREDICT` INT, `HISTORY_RESULT` INT, `PNL` INT, `FAVORITE` INT, `TAGS` INT, `NOTE` INT, `IS_UNSOLVED` INT, `IS_CORRECT` INT, `IS_WRONG` INT);

-- -----------------------------------------------------
-- View `mydb`.`v_history_base`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`v_history_base`;
USE `mydb`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`goldSys`@`localhost` SQL SECURITY DEFINER VIEW `mydb`.`v_history_base` AS select `h`.`HISTORY_NO` AS `HISTORY_NO`,`h`.`MEMBER_NO` AS `MEMBER_NO`,`h`.`HISTORY_DATE` AS `HISTORY_DATE`,`h`.`HISTORY_PREDICT` AS `HISTORY_PREDICT`,`h`.`HISTORY_RESULT` AS `HISTORY_RESULT`,`h`.`PNL` AS `PNL`,`h`.`FAVORITE` AS `FAVORITE`,`h`.`TAGS` AS `TAGS`,`h`.`NOTE` AS `NOTE`,(`h`.`HISTORY_RESULT` is null) AS `IS_UNSOLVED`,((`h`.`HISTORY_RESULT` is not null) and (`h`.`HISTORY_RESULT` = `h`.`HISTORY_PREDICT`)) AS `IS_CORRECT`,((`h`.`HISTORY_RESULT` is not null) and (`h`.`HISTORY_RESULT` <> `h`.`HISTORY_PREDICT`)) AS `IS_WRONG` from `mydb`.`simulation_history` `h`;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
